import contextlib
import io
import json
import sys
import tempfile
import unittest
from pathlib import Path


SCRIPTS = Path(__file__).resolve().parents[1] / "scripts"
sys.path.insert(0, str(SCRIPTS))

import verify_release  # noqa: E402


LEGACY_ADAPTER = "legacy-build-sh-arm64-v1"
KLEAF_FRAGMENT_ADAPTER = "kleaf-defconfig-fragment-arm64-v1"


class VerifyReleaseTests(unittest.TestCase):
    def write_plan(
        self,
        directory: Path,
        *,
        adapter: str = KLEAF_FRAGMENT_ADAPTER,
        base_release: str = "6.1.175",
        suffix: str = "-ReNebula-v2-a14-6.1-none",
        legacy_family_id: str = "android12-5.10",
    ) -> Path:
        if adapter == LEGACY_ADAPTER:
            family_id = legacy_family_id
            release_id = f"{family_id}-test"
            build = {
                "adapter": adapter,
                "image_name": "Image",
                "build_config": "common/build.config.gki.aarch64",
            }
            release_contract = {
                "mode": "exact",
                "expected_uname_release": base_release + suffix,
            }
        elif adapter == KLEAF_FRAGMENT_ADAPTER:
            family_id = "android14-6.1"
            release_id = "android14-6.1-test"
            build = {
                "adapter": adapter,
                "image_name": "Image",
                "bazel_target": "//common:kernel_aarch64_dist",
            }
            release_contract = {
                "mode": "base-prefix-and-suffix",
                "prefix": base_release,
                "suffix": suffix,
            }
        else:
            raise AssertionError(f"unexpected adapter in test setup: {adapter}")

        path = directory / "build-plan.json"
        path.write_text(
            json.dumps(
                {
                    "schema": 2,
                    "selection": {
                        "family_id": family_id,
                        "release_id": release_id,
                        "state": "source-locked",
                        "root": "none",
                        "features": [],
                    },
                    "source": {"lock_id": f"gki.{family_id}.test"},
                    "build": build,
                    "version": {
                        "expected_base_release": base_release,
                        "local_suffix": suffix,
                        "release_contract": release_contract,
                    },
                }
            ),
            encoding="utf-8",
        )
        return path

    def write_makefile(self, directory: Path, base_release: str) -> Path:
        version, patchlevel, sublevel = base_release.split(".")
        path = directory / "Makefile"
        path.write_text(
            f"VERSION = {version}\nPATCHLEVEL = {patchlevel}\nSUBLEVEL = {sublevel}\n",
            encoding="utf-8",
        )
        return path

    def test_fragment_kleaf_plan_writes_fragment_and_accepts_google_provenance_segment(self):
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            suffix = "-ReNebula-v2-a14-6.1-none"
            plan = self.write_plan(directory, suffix=suffix)
            makefile = self.write_makefile(directory, "6.1.175")
            fragment = directory / "renebula" / "localversion_defconfig"
            build_file = directory / "renebula" / "BUILD.bazel"
            image = directory / "Image"
            observed_release = "6.1.175-google-gki" + suffix
            image.write_bytes(f"prefix\x00Linux version {observed_release} build\x00".encode())
            record = directory / "build-record.json"

            result = verify_release.main(
                [
                    "--plan",
                    str(plan),
                    "--makefile",
                    str(makefile),
                    "--write-fragment",
                    str(fragment),
                    "--write-build-file",
                    str(build_file),
                    "--image",
                    str(image),
                    "--record",
                    str(record),
                ]
            )

            self.assertEqual(result, 0)
            self.assertEqual(
                fragment.read_text(encoding="utf-8"),
                "# Generated by scripts/verify_release.py; do not hand-edit.\n"
                'CONFIG_LOCALVERSION="-ReNebula-v2-a14-6.1-none"\n'
                "# CONFIG_LOCALVERSION_AUTO is not set\n",
            )
            self.assertIn('exports_files(["localversion_defconfig"])', build_file.read_text())
            record_data = json.loads(record.read_text(encoding="utf-8"))
            self.assertEqual(record_data["schema"], 2)
            self.assertEqual(record_data["observed_uts_release"], observed_release)
            self.assertEqual(
                record_data["release_contract"],
                {
                    "mode": "base-prefix-and-suffix",
                    "prefix": "6.1.175",
                    "suffix": suffix,
                },
            )

    def test_legacy_plan_writes_export_and_post_defconfig_contract(self):
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            suffix = "-ReNebula-v2-a12-5.10-none"
            plan = self.write_plan(
                directory,
                adapter=LEGACY_ADAPTER,
                base_release="5.10.260",
                suffix=suffix,
            )
            makefile = self.write_makefile(directory, "5.10.260")
            script = directory / "renebula" / "apply-localversion.sh"
            build_config = directory / "renebula" / "localversion.build.config"
            image = directory / "Image"
            observed_release = "5.10.260" + suffix
            image.write_bytes(f"Linux version {observed_release} builder\x00".encode())

            result = verify_release.main(
                [
                    "--plan",
                    str(plan),
                    "--makefile",
                    str(makefile),
                    "--write-legacy-script",
                    str(script),
                    "--write-legacy-build-config",
                    str(build_config),
                    "--image",
                    str(image),
                ]
            )

            self.assertEqual(result, 0)
            script_contents = script.read_text(encoding="utf-8")
            self.assertIn('config_path="${1:?missing kernel .config path}"', script_contents)
            self.assertIn(
                'LOCALVERSION_AUTO --set-str LOCALVERSION "-ReNebula-v2-a12-5.10-none"',
                script_contents,
            )
            self.assertIn('make -C "$kernel_dir" O="$out_dir" olddefconfig', script_contents)
            self.assertNotIn("setlocalversion", script_contents)
            self.assertEqual(
                build_config.read_text(encoding="utf-8"),
                "# Generated by scripts/verify_release.py; do not hand-edit.\n"
                "# Keep scripts/setlocalversion from adding a Git-derived '+' suffix.\n"
                'export LOCALVERSION=""\n'
                "append_cmd POST_DEFCONFIG_CMDS "
                "'${ROOT_DIR}/renebula/apply-localversion.sh \"${OUT_DIR}/.config\"'\n",
            )

    def test_android13_legacy_plan_uses_an_exact_release_contract(self):
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            suffix = "-ReNebula-v2-a13-5.10-none"
            plan = self.write_plan(
                directory,
                adapter=LEGACY_ADAPTER,
                base_release="5.10.260",
                suffix=suffix,
                legacy_family_id="android13-5.10",
            )
            makefile = self.write_makefile(directory, "5.10.260")
            image = directory / "Image"
            image.write_bytes(f"Linux version 5.10.260{suffix} builder\x00".encode())

            result = verify_release.main(
                ["--plan", str(plan), "--makefile", str(makefile), "--image", str(image)]
            )

            self.assertEqual(result, 0)

    def test_rejects_a_suffix_that_repeats_the_base_release(self):
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            plan = self.write_plan(directory, suffix="-6.1.175-ReNebula")
            makefile = self.write_makefile(directory, "6.1.175")

            with contextlib.redirect_stderr(io.StringIO()):
                result = verify_release.main(["--plan", str(plan), "--makefile", str(makefile)])

            self.assertEqual(result, 2)

    def test_rejects_an_image_with_the_wrong_kleaf_release_boundary(self):
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            plan = self.write_plan(directory)
            makefile = self.write_makefile(directory, "6.1.175")
            image = directory / "Image"
            image.write_bytes(b"Linux version 6.1.175-foreign user\x00")

            with contextlib.redirect_stderr(io.StringIO()):
                result = verify_release.main(
                    ["--plan", str(plan), "--makefile", str(makefile), "--image", str(image)]
                )

            self.assertEqual(result, 2)

    def test_rejects_a_kleaf_image_with_a_double_base_prefix(self):
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            suffix = "-ReNebula-v2-a14-6.1-none"
            plan = self.write_plan(directory, suffix=suffix)
            makefile = self.write_makefile(directory, "6.1.175")
            image = directory / "Image"
            image.write_bytes(
                f"Linux version 6.1.175-gki-6.1.175{suffix} builder\x00".encode()
            )

            with contextlib.redirect_stderr(io.StringIO()):
                result = verify_release.main(
                    ["--plan", str(plan), "--makefile", str(makefile), "--image", str(image)]
                )

            self.assertEqual(result, 2)
